### ISSUE TITLE
Module not Found

### ISSUE THREAD

**Issue by sseodate** [jhuckaby/performa#26]
I try to install performa to new server but this time i got this error.

/opt/performa/bin/control.sh start
/opt/performa/bin/control.sh start: Starting up Performa Daemon...
Error: Cannot find module 'node:fs'
Require stack:
- /opt/performa/node_modules/formidable/dist/index.cjs
- /opt/performa/node_modules/pixl-server-web/lib/https.js
- /opt/performa/node_modules/pixl-server-web/web_server.js
- /opt/performa/lib/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/opt/performa/node_modules/formidable/dist/index.cjs:5:10)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/performa/node_modules/formidable/dist/index.cjs',
    '/opt/performa/node_modules/pixl-server-web/lib/https.js',
    '/opt/performa/node_modules/pixl-server-web/web_server.js',
    '/opt/performa/lib/main.js'
  ]
}

What should i do to fix this?

**Comment by jhuckaby** [comment]
Your Node.js is too old.  You will need to upgrade to Node.js v16 or higher.
